
<?php 

$title = "Ajouter un Meetup"; 

$this->headTitle($title); 

?>

<h2><?=$this->escapeHtml($title)?></h2>
  <div class="form-group">
	<?php 

		$form->setAttribute('action', $this->url('meeting', ['action' => 'add'])); 
		$form->prepare(); 

		echo $this->form()->openTag($form); 
		echo $this->formHidden($form->get('id')); 

		echo $this->formRow($form->get('titre'));
		echo "<br>";
		echo $this->formRow($form->get('organisateur'));
		echo "<br>";
		echo $this->formRow($form->get('organisation'));
		echo "<br>";
		echo $this->formRow($form->get('description'));
		echo "<br>";
		echo $this->formRow($form->get('dateDebut'));
		echo "<br>";
		echo $this->formRow($form->get('dateFin'));
	?>
	<br>

	<?php 
		echo $this->formSubmit($form->get('submit'));
		echo $this->form()->closeTag();
 ?>
</div>